import os
import cv2
import numpy as np

def rotate_with_pbc(image, angle, final_size=512):
    """
    Rotate image with periodic boundary condition and crop to final size.
    Parameters:
        image: input 2D grayscale image
        angle: rotation angle in degrees
        final_size: output image size (final_size x final_size)
    Returns:
        Cropped rotated image with size (final_size x final_size)
    """
    h, w = image.shape
    min_len = min(h, w)
    image_cropped = image[0:min_len, 0:min_len]

    image_resized = cv2.resize(image_cropped, (final_size, final_size), interpolation=cv2.INTER_AREA)

    pad = int(np.ceil(np.sqrt(2) * final_size))
    padded = np.pad(image_resized, ((pad, pad), (pad, pad)), mode='wrap')

    center = (padded.shape[1] // 2, padded.shape[0] // 2)
    rot_mat = cv2.getRotationMatrix2D(center, angle, 1.0)
    rotated = cv2.warpAffine(padded, rot_mat, (padded.shape[1], padded.shape[0]),
                             flags=cv2.INTER_LINEAR)

    start = (rotated.shape[0] - final_size) // 2
    cropped = rotated[start:start + final_size, start:start + final_size]
    return cropped


def rotate_images_with_pbc(base_path, ori_file_dir, angle_list):
    """
    Perform rotation on shifted images using PBC and save results in the same directory.
    The output filenames preserve the original index-based format used by shift_main.py.
    Format: {index}_shift-XXpx_rot-YYdeg.png
    """
    file_dir_path = os.path.join(base_path, ori_file_dir)
    all_files = sorted(os.listdir(file_dir_path))

    # Only use images that were generated by shift_main (e.g., '1_shift-8px.png')
    file_list = [f for f in all_files if '_shift-' in f and f.endswith('.png')]

    print('===================================================================')
    print(f'[INFO] Rotated images will be saved in: {file_dir_path}')
    print('[INFO] Number of shifted images:', len(file_list))
    print('[INFO] Rotation angles:', angle_list)

    for i, filename in enumerate(file_list):
        file_path = os.path.join(file_dir_path, filename)
        print(f'[{i+1}/{len(file_list)}] Processing: {filename}')

        img = cv2.imread(file_path, cv2.IMREAD_GRAYSCALE)
        if img is None:
            print(f'[WARNING] Failed to load image: {file_path}')
            continue

        for angle in angle_list:
            rot_img = rotate_with_pbc(img, angle)

            name_wo_ext = os.path.splitext(filename)[0]           # "1_shift-8px"
            angle_str = str(angle).replace('.', 'p')              # 22.5 → 22p5
            save_name = f'{name_wo_ext}_rot-{angle_str}deg.png'   # e.g., "1_shift-8px_rot-22p5deg.png"
            save_path = os.path.join(file_dir_path, save_name)

            cv2.imwrite(save_path, rot_img)

    print('[INFO] Rotation completed for all images.')
    print('===================================================================')


# === Example run ===
if __name__ == '__main__':
    base_path = os.getcwd()
    ori_file_dir = 'ori_png/'              # Folder with shifted images (e.g., 1_shift-8px.png)
    angle_list = [5, 10, 15, 20, 25, 30]   # Rotation angles in degrees

    rotate_images_with_pbc(base_path, ori_file_dir, angle_list)

